name: Lint Code Base

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      # From https://github.com/marketplace/actions/lint-action#python-example-flake8-and-black
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: pip install black

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          auto_fix: true
          black: true
          black_auto_fix: true
